### ISSUE TITLE
Figure out how to extract recommendations.

### ISSUE THREAD

**Issue by Scribblets** [IBM-Bluemix/hotel-iot-backend#16]
So, this is going in for the Recommendations API service.

I'm basically trying to figure out how to aggregate all of that data into a pretty response. Been working with promises and mostly fiddling with the data flow at the moment.
# Tasks
- [ ] Sample the user's last 500-1,000 tweets.
- [x] Get entities from tweets, concepts, AND keywords.
- [ ] Score tweets based on recurring entities to figure out the user's interests.
- [ ] Store location data to track where they've been in the past. (Use the given hotel information to determine whether or not they've been to this location / city before. If they have, what kind of places did they go to last time?)
- [ ] Order any relevant information by time. For example,  if all of their tweets indicate they like Italian Food and Mexican Food, and they had Mexican Food recently, try suggesting an Italian place. (Most people don't want to eat the same thing twice in a row.) Use **time** and **entity score** to determine which recommendation to provide.
- [ ] Use the provided location data of the hotel to search the local area in whatever API is used.
