### ISSUE TITLE
Create Twitter account for Persona

### ISSUE THREAD

**Issue by Scribblets** [IBM-Bluemix/hotel-iot-backend#19]
# Tasks
- [ ] Create Twitter account
- [ ] Find avatar for persona
- [ ] Find interests, and select accounts to follow.
- [ ] Make posts / upload image regarding his interests.
