### ISSUE TITLE
Write Recommendations API

### ISSUE THREAD

**Issue by Scribblets** [IBM-Bluemix/hotel-iot-backend#4]
As a **developer**, I can use **an API** to gather data about the user so that I can **provide recommendations based on their interests**.
# Tasks
- [x]  #5 Write API Routes (will be adding to this continuously)
- [x] #7 Setup Environment Variables
- [x] #17 Train Watson Conversation
- [ ] #16 Figure out how to extract recommendations
- [x] #2 Get Data pulling from Twitter
- [ ] Get Data pulling from Pinterest
- [x] #15 Pull keywords from Watson Alchemy
- [x] #15 Pull concepts from Watson Alchemy
