### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by Scribblets** [IBM-Bluemix/hotel-iot-backend#7]
As a **developer**, I can store all of my API keys safely in an environment variable.
# Tasks
- [x] #6 Add Twitter Keys to Environment Variables
- [x] #8 Add IoT Keys to Environment Variables
- [x] #9 Add DB Credentials to Environment Variables
- [x] #13 Add Watson Personality Insights Credentials to Environment Variables
